# Kalman Filter Simple Steps

First, let's start with 2-D.

1. Calculate Kalman Gain. $$ KG = \frac{E_{EST}}{E_{EST} + E_{MEA}}$$ where $E_{EST}$ means an Error in Estimate and $E_{MEA}$ means an error in measurement. Please notice $$ 0 <= KG <= 1 $$
2. Compute a next Estimate. $$EST_{t} = EST_{t - 1} + KG(MEA - EST_{t -1})$$
3. Compute a new error in estimate. 
\begin{align*}
E_{EST_t} &= \frac{E_{MEA} \cdot E_{EST_{t-1}} } { E_{MEA} + E_{EST_{t-1}}} \\
                &= (1 - KG) \cdot E_{EST_{t-1}}
\end{align*}

## Simple Example
- Suppose there is a thermostat that measure a room's temperature
- True Temperature: 72
- Initial Guess(Estimate): 60
- Measurement: 75
- Error in Estimate: 2
- Error in Measurement: 4

In [1]:
import numpy as np

In [2]:
def get_kalman_gain(err_estimate, err_measure):
    return err_estimate / (err_estimate + err_measure)

def get_new_estimate(KG, previous_estimate, measurement):
    return previous_estimate + KG * (measurement - previous_estimate)

def get_new_estimate_error(KG, previous_error):
    return (1 - KG) * previous_error

#### We can see every several steps it approaches to the true temperature eventually.

In [3]:
estimate = 60
size = 1000
measurement = np.random.normal(loc = 72, scale = 4, size = size)
error_estimate = 2
error_measure = 4

for i, measurement in enumerate(measurement):
    KG = get_kalman_gain(error_estimate, error_measure)
    estimate = get_new_estimate(KG, estimate, measurement)
    error_estimate = get_new_estimate_error(KG, error_estimate)
        
    msg = f"""

Kalman Gain: {KG}
Measurement: {measurement}
Estimate: {estimate}
----------------------
True Value: {72}
----------------------
Error in Estimate: {error_estimate}
    """
    
    
    if i % size // 10 == 0 or i == size -1 or i == 0:
        #print(msg)
        print(f"Estimate: {estimate}")
    

Estimate: 63.66992340010672
Estimate: 66.57172829318046
Estimate: 67.57520785069819
Estimate: 68.73452440629119
Estimate: 68.85865705531286
Estimate: 69.23812686691292
Estimate: 69.64975555658053
Estimate: 70.01166255407522
Estimate: 70.2996315327791
Estimate: 70.75936061363731
Estimate: 71.95270176617466


The easy way to see how it works is to visualize in a table

Assume the initial estimate is 68 and measurements are [75, 71, 70].

|     | $MEA$ | $E_{MEA}$ | $EST$ | $E_{EST_{t-1}}$ | $KG$ | $E_{EST_t}$ |
|----|-----------|----------------|---------|---------------------|----------|-----------------|
|$t-1$|              |                     |     68       |       2                    |            |                      |      
|$t    $|      75        |         4            |       70.33     |                           |     0.33          |   1.33                     |
|$t+1$|      71        |        4             |     70.50       |                           |     0.25         |    1.00                  |
|$t+2$|       70       |       4              |       70.40     |                           |     0.20          |    0.80                  |

## Multi-dimensional Kalman Filter

First of all, I'm going to write down the whole process first and explain each step in details later.

1. There is an initial state X such as $$\mathbf{X_0} = \begin{bmatrix} 
                                                                    X_0 \\
                                                                    P_0
                                                           \end{bmatrix}         $$

2. Then, we can get a new state or predicted state:
$$\begin{align}
\mathbf{X_{t_p}} &= \mathbf{A} \cdot \mathbf{X_{t-1}} + \mathbf{B} \cdot \mathbf{u_t} + \mathbf{w_t} \\
\mathbf{P_{t_p}} &= \mathbf{A} \cdot  \mathbf{ P_{t-1}} \mathbf{A^T} + \mathbf{Q_t} \\
\end{align}$$
where 
    - $\mathbf{X_{t_p}}$: New Predicted State
    - $\mathbf{u_k}$: Control Variable like acceleration, gravity, etc.
    - $\mathbf{w}$: Predicted State Noise Matrix
    - $\mathbf{Q}$: Process noise Covariance Matrix    
    - $\mathbf{P}$: Process Covariance Matrix (Represents an error in estimate)    
    - $\mathbf{A}, \mathbf{B}, ...$: a helper matrix (State Transition Matrix, Control Input Matrix, ...)

3. Update Kalman Gain:
$$
    \begin{align}
        \mathbf{K} &= \frac{\mathbf{P_{t_p}} \cdot \mathbf{H}} {\mathbf{H} \cdot \mathbf{P_{t_p}} \cdot \mathbf{H^T} + \mathbf{R}} \\
        \mathbf{X_t} &= \mathbf{X_{t_p}} + \mathbf{K}[\mathbf{Y} - \mathbf{H} \cdot \mathbf{X_{t_p}} ]
    \end{align}
$$
where
$$
    \begin{align}
        \mathbf{Y_t} &= \mathbf{C} \cdot \mathbf{X_{t_m}} + \mathbf{Z_t}
     \end{align}
$$
where
    - $\mathbf{R}$: Sensor Noise Covariance Matrix (Error in Measurement)
    - $\mathbf{Z_t}$: Uncertainty
    - $\mathbf{C}$: the transformation matrix that maps the state vector parameters into the measurement domain
4. Update new $\mathbf{P_t}$ and $\mathbf{X_t}$:
$$
    \begin{align}
        \mathbf{P_t} &= \left( \mathbf{I} - \mathbf{K} \cdot \mathbf{H} \right) \cdot \mathbf{P_{t_p}} \\
        \mathbf{X_t}
    \end{align}
$$
5. Repeat from step 2 again.

## Covariance Matrix Example

Covariance matrix plays a key role in kalman filter. So, let's quickly review one example.

Suppose there are two random variables, $\mathbf{X}$ and $\mathbf{Y}$.

\begin{align*}
    Var(X) &= \frac{1}{N} \sum_i^N (x_i - \bar{x_i})^2 \\ \\
    Cov(X, Y) &= \frac{1}{N} \sum_i^N (x_i - \bar{x_i})(y_i - \bar{y_i})     
\end{align*}

$Cov(X, Y)$ can be also written as $\sigma_{XY}$.

#### Example. 

Each column means one randome variable, say $\mathbf{X}, \mathbf{Y}, \mathbf{Z}$.

In [4]:
A = np.array([[ 4.  ,  2.  ,  0.6    ],
                       [ 4.2 ,  2.1 ,  0.59],
                       [ 3.9 ,  2.  ,  0.56 ],
                       [ 4.3 ,  2.1 ,  0.62],
                       [ 4.1 ,  2.3 ,  0.63]])
mean_list = np.mean(A, axis=0)
mean_list

array([ 4.1,  2.1,  0.6])

In [5]:
A_mean_subtracted = A - mean_list
A_mean_subtracted

array([[-0.1 , -0.1 ,  0.  ],
       [ 0.1 ,  0.  , -0.01],
       [-0.2 , -0.1 , -0.04],
       [ 0.2 ,  0.  ,  0.02],
       [ 0.  ,  0.2 ,  0.03]])

In [6]:
var_X = np.var(A, axis=0)
cov_XY = np.mean(A_mean_subtracted[:, 0] * A_mean_subtracted[:, 1])
cov_XZ = np.mean(A_mean_subtracted[:, 0] * A_mean_subtracted[:, 2])
cov_YZ = np.mean(A_mean_subtracted[:, 1] * A_mean_subtracted[:, 2])

print ("Variance: {}".format(var_X))
print ("Cov(X, Y): {:.4f}".format(cov_XY))
print ("Cov(X, Z): {:.4f}".format(cov_XZ))
print ("Cov(Y, Z): {:.4f}".format(cov_YZ))

Variance: [ 0.02    0.012   0.0006]
Cov(X, Y): 0.0060
Cov(X, Z): 0.0022
Cov(Y, Z): 0.0020


In [7]:
np.cov(A, rowvar=False, bias=True) # check if we get the same value 

array([[ 0.02  ,  0.006 ,  0.0022],
       [ 0.006 ,  0.012 ,  0.002 ],
       [ 0.0022,  0.002 ,  0.0006]])

#### Another way to calculate covariance matrix by linear algebra

Say there is a matrix with M obeservations and N variables. Then, 

$$ \text{Covariance Matrix} =  \frac{\mathbb{a}^T \mathbb{a}} {M}  $$

where $$a = A - ones(M, M) \cdot A \cdot \left( \frac{1}{M} \right)$$

a is called a deviation matrix

In [8]:
a = A - np.ones(shape = (A.shape[0], A.shape[0])).dot(A) / A.shape[0]
a.transpose().dot(a)/A.shape[0]

array([[ 0.02  ,  0.006 ,  0.0022],
       [ 0.006 ,  0.012 ,  0.002 ],
       [ 0.0022,  0.002 ,  0.0006]])

In [9]:
## or use broadcast
a = A - np.mean(A, axis=0)
a.transpose().dot(a)/A.shape[0]

array([[ 0.02  ,  0.006 ,  0.0022],
       [ 0.006 ,  0.012 ,  0.002 ],
       [ 0.0022,  0.002 ,  0.0006]])

## Real Example

1. $x_0 = 50$ $m$
2. $\dot{x_0} = v_0 = 5$ $m/sec$
3. $a_0 = 2$ $m/sec^2$

There is a $X$ such that
$$ X = \begin{bmatrix} x\\ \dot{x} \end{bmatrix} $$

And process variation standard deviation is given

1. $\sigma_x = 0.5m$
2. $\sigma_{\dot{x}} = 0.2m/sec$
3. For simplicity, we just make a guess such that $\sigma_{x\dot{x}} = \sigma_x \cdot \sigma_{\dot{x}} = 0.1$
    - However, it's important to know $$Correlation(X, Y) = \frac{Cov(X, Y)}{SD(X) SD(Y)}$$ we're just making a guess here.

There is a $P$($P$ stands for Process or Estimate Error) such that
$$ 
\begin{align}
P &= \begin{bmatrix}
                    \sigma_x^2    &    \sigma_{x\dot{x}} \\
                    \sigma_{\dot{x}x}    &    \sigma_{\dot{x}}^2 \\
            \end{bmatrix} \\
 P_0   &= \begin{bmatrix}
                    0.25 & 0.1 \\
                    0.1 & 0.04
            \end{bmatrix} \\
\end{align}
$$

## Tracking an airplane example

Given Information:

- $x_0 = 4000\ m$
- $v_{x_0} = 280\ m/\sec$
- $v_{y_0} = 120\ m/\sec$

Observations:

|       | $x_0$                |  $v_{x_0}$          |
|-----|-------- |-----------------|
|0   |4,000 | 280|
|1   |4,260 | 282|
|2   |4,550 | 285|
|3   |4,860 | 286|
|4   |5,110 | 290|


Initial Conditions:

| $a_x$ | $v_x$ | $\Delta t$ | $\Delta x $ |
|---------|---------|----------------|------------------|
|2 $m/sec^2$|280 $m/sec$|1 $sec$|25 $m$|

Process Errors in Process Covariance Matrix:
\begin{align}
        \Delta P_x       &= 20 \\
        \Delta P_{v_x} &= 5
\end{align}

Observation Errors:

\begin{align}
    \Delta x       &= 25 &\text{ (observation error) }\\
    \Delta v_{x} &= 6
\end{align}

# Step by Step Explanation
First we will assume it's one dimension (it's almost identical to make it 2-D coordinates). We also assume the error is zero which means $w_k = 0$.

#### 1. Calculate the predicted state.

$$
\begin{align}
X_{t_p} &=   A X_{t-1} + B u_t + w_t \\
             &= \begin{bmatrix}
                         1 & \Delta t \\
                         0 & 1 \\
                    \end{bmatrix}                \begin{bmatrix} 
                                                                        X_0 \\
                                                                        V_{X_0} \\
                                                             \end{bmatrix}        + \begin{bmatrix}   
                                                                                                         \frac{1}{2} \Delta t^2 \\
                                                                                                         \Delta t \\
                                                                                                 \end{bmatrix}  \left[ a_{X_0} \right] + 0 
\end{align}
$$

In [10]:
A = np.array([[1, 1], [0, 1]])
X = np.array([[4000], [280]])
B = np.array([[0.5], [1]])
u = 2

print ("""A=
{}
X=
{}
B=
{}
u={}
""".format(A, X, B, u))

X = A.dot(X) + B * u
print("Predicted (new) State:\n", X)

A=
[[1 1]
 [0 1]]
X=
[[4000]
 [ 280]]
B=
[[ 0.5]
 [ 1. ]]
u=2

Predicted (new) State:
 [[ 4281.]
 [  282.]]


#### 2. Calculate Process Covariance Matrix (P)

$$P_{k-1} = \begin{bmatrix}
                            \sigma_x^2    &    \sigma_{xv} \\
                            \sigma_{vx}    &    \sigma_v^2 \\
                     \end{bmatrix} $$

In [11]:
P = np.array([[20*20, 20 * 5],
                       [5 * 20, 5 * 5 ]])

# To make it simple, we will assume there is zero covaraiance though.
P = np.array([[400, 0],
                       [0,    25]])

#### 3. Calculate predicted process covriance matrix

$$P_{k_p} = A \cdot P_{k-1} \cdot A^T + Q_k$$

$Q$ is a process covariance noise but we will assume it to be zero here.

In [12]:
new_P = A.dot(P).dot(A.transpose()) - np.fliplr(np.diag(np.diag(np.fliplr(A.dot(P).dot(A.transpose()) ))))
print("Predicted P = ", new_P, sep='\n')

Predicted P = 
[[425   0]
 [  0  25]]


#### 4. Calculate the Kalman Gain
$$ K = \frac{P_{k_p}  \cdot H^T}{ H \cdot P_{k_p} \cdot H^T + R } $$

- $H$: just keeps the dimension of P matched to the dimension of Kalman Gain. Hence it's identity matrix (2 x 2) here.
- $R$: measurement(observation) error
    - We were assuming that $\Delta x = 25$ and $\Delta v_x = 6$
    - Therefore, $R = \begin{bmatrix}
                                        25 * 25 & 0 \\
                                        0 & 6 * 6 \end{bmatrix} $

In [13]:
P = new_P
R = np.array([[25*25, 1e-7], [1e-7, 6*6]])
H = np.identity(2)
K = P.dot(H.transpose()) / (H.dot(P).dot(H.transpose()) + R)
print("Kalman Gain Matrix = ", K, sep="\n")

Kalman Gain Matrix = 
[[ 0.4047619   0.        ]
 [ 0.          0.40983607]]


Since $K << 1$, it implies we don't want to heavily depend on observations.

#### 5. New observation
$$ Y_k = C \cdot Y_{k_m} + Z_k $$

- $Z_k$: uncertainty (assuming it to be zero)
- $C$: is just a mapping function to keep the dimension correct, so 2 x 2 identity matrix here

In [14]:
C = np.identity(2)
new_Y = np.array([[4260], [282]])
Y = C.dot(new_Y)
print("Y = ", Y, sep='\n')

Y = 
[[ 4260.]
 [  282.]]


#### 6. Finally, we can calculate the current state

$$ X_k = X_{k_p} + K[Y_k - H \cdot X_{k_p} ] $$

In [15]:
X_real = X + K.dot(Y - H.dot(X))
print("Current State:")
print(X_real)

Current State:
[[ 4272.5]
 [  282. ]]


#### 7. Update the process covariance matrix for a next iteration

$$ P_k = (I - KH) P_{k_p} $$

In [16]:
P_real = (np.identity(2) - K.dot(H)).dot(P)
print("P real:")
print(P_real)

P real:
[[ 252.97619048    0.        ]
 [   0.           14.75409836]]


#### 8. Finished one iteration. Now we have to repeat 

- $X_{k_p} = A X_{k-1} + B u_k + w_k$
- $P_{k_p} = A P_{k-1} A^T + Q_k $

In [17]:
X_pred = A.dot(X_real) + B.dot(u)
P_pred = A.dot(P_real).dot(A.transpose())

print ("X_pred: ")
print(X_pred)

print("P_pred: ")
print(P_pred)

X_pred: 
[[ 4555.5]
 [  284. ]]
P_pred: 
[[ 267.73028884   14.75409836]
 [  14.75409836   14.75409836]]


In [18]:
## All in one
def predict_state_process(A, X, B, u, P, w = 0, q = 0):
    X_pred = A.dot(X) + B.dot(u) + w
    P_pred = A.dot(P).dot(A.transpose()) + q
    
    return [X_pred, P_pred]

def get_kalman_gain(P, H, R):
    return P.dot(H.transpose()) / (H.dot(P).dot(H.transpose()) + R)

def get_observation(C, Y, z = 0):
    return C.dot(Y) + z

def get_real_state_process(X, K, Y, H, P):
    X_real = X + K.dot(Y - H.dot(X))
    P_real = (np.identity(np.shape(K.dot(H))[0]) - K.dot(H)).dot(P)
    
    return X_real, P_real

In [19]:
observations = np.array([
    [4000, 280],
    [4260, 282],
    [4550, 285],
    [4860, 286],
    [5110, 290]
])

In [20]:
A = np.array([[1, 1], [0, 1]])
X = observations[0].reshape(-1, 1)
B = np.array([[0.5], [1]])
u = 2
P = np.array([[400, 0],
                       [0,    25]])
for i in range(len(observations) - 1):
    X, P = predict_state_process(A, X, B, u, P)
    P[0, 1] = 0 #keep independent
    P[1, 0] = 0 #keep independent
    H = np.identity(2)
    K = get_kalman_gain(P, H, R)
    C = np.identity(2)
    Y = get_observation(C, Y=observations[i+1].reshape(-1, 1))
    X, P = get_real_state_process(X, K, Y, H, P)

    print("==========================================")    
    print("X state: ")
    print(X)    
    print("------------------------------------------")
    print("P state:")
    print(P)

X state: 
[[ 4272.5]
 [  282. ]]
------------------------------------------
P state:
[[ 252.97619048    0.        ]
 [   0.           14.75409836]]
X state: 
[[ 4553.85054707]
 [  284.29069767]]
------------------------------------------
P state:
[[ 187.4378327     0.        ]
 [   0.           10.46511628]]
X state: 
[[ 4844.15764332]
 [  286.22522523]]
------------------------------------------
P state:
[[ 150.30854278    0.        ]
 [   0.            8.10810811]]
X state: 
[[ 5127.05898493]
 [  288.55147059]]
------------------------------------------
P state:
[[ 126.38282157    0.        ]
 [   0.            6.61764706]]
